---
# tasks file for roles/motd
#
- name: display post install message seeing how many chars this can holdd
  debug:
    msg:
      - 'Thank you for choosing -----'
  run_once: true

- pause:
    seconds: 20

